name: Telegram Self-Bot Runner

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 */5 * * *'

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Bot
      env:
        # نام متغیرها باید دقیقاً با نام سکرت‌های ثبت شده در گیت‌هاب یکسان باشد
        API_ID: ${{ secrets.API_ID }}
        API_HASH: ${{ secrets.API_HASH }}
        STRING_SESSION: ${{ secrets.STRING_SESSION }}
        CONFIG_CHANNEL_ID: ${{ secrets.CONFIG_CHANNEL_ID }}
      run: |
        python main.py
